In [3]:
import numpy as np

In [4]:
N = 5

In [50]:
grid = np.zeros((N, N), int)
grid[1][2] = 8
grid[3][2] = 2
grid[0][1] = 1
grid[2][3] = 4
grid[1][4] = 2
grid[4][3] = 8
grid[3][1] = 1
grid

array([[0, 1, 0, 0, 0],
       [0, 0, 8, 0, 2],
       [0, 0, 0, 4, 0],
       [0, 1, 2, 0, 0],
       [0, 0, 0, 8, 0]])

In [36]:
def right(i, j, grid):
    if(j==N-1):
        grid[i][0] |= 1
    else:
        grid[i][j+1] |= 1

In [37]:
def up(i, j, grid):
    if(i==0):
        grid[N-1][j] |= 2
    else:
        grid[i-1][j] |= 2 

In [38]:
def left(i, j, grid):
    if(j==0):
        grid[i][N-1] |= 4
    else:
        grid[i][j-1] |= 4

In [39]:
def down(i, j, grid):
    if(i==N-1):
        grid[0][j] |= 8
    else:
        grid[i+1][j] |= 8

In [40]:
def move(grid):
    newgrid = np.zeros((N, N), int)
    for i, row in enumerate(grid):
        for j, val in enumerate(row):
            if(val==1):
                right(i, j, newgrid)
            elif(val==2):
                up(i, j, newgrid)
            elif(val==4):
                left(i, j, newgrid)
            elif(val==8):
                down(i, j, newgrid)
            elif(val==3):
                up(i, j, newgrid)
                right(i, j, newgrid)
            elif(val==9):
                right(i, j, newgrid)
                down(i, j, newgrid)
            elif(val==6):
                left(i, j, newgrid)
                up(i, j, newgrid)
            elif(val==12):
                left(i, j, newgrid)
                down(i, j, newgrid)
            elif(val==5):
                up(i, j, newgrid)
                down(i, j, newgrid)
            elif(val==10):
                left(i, j, newgrid)
                right(i, j, newgrid)
            elif(val==7):
                left(i, j, newgrid)
                up(i, j, newgrid)
                right(i, j, newgrid)
            elif(val==11):
                up(i, j, newgrid)
                down(i, j, newgrid)
                right(i, j, newgrid)
            elif(val==13):
                down(i, j, newgrid)
                left(i, j, newgrid)
                right(i, j, newgrid)
            elif(val==14):
                left(i, j, newgrid)
                up(i, j, newgrid)
                down(i, j, newgrid)
            elif(val==15):
                right(i, j, newgrid)
                up(i, j, newgrid)
                left(i, j, newgrid)
                down(i, j, newgrid)
    return newgrid

In [51]:
grid

array([[0, 1, 0, 0, 0],
       [0, 0, 8, 0, 2],
       [0, 0, 0, 4, 0],
       [0, 1, 2, 0, 0],
       [0, 0, 0, 8, 0]])

In [52]:
grid = move(grid)
grid

array([[ 0,  0,  1,  8,  2],
       [ 0,  0,  0,  0,  0],
       [ 0,  0, 14,  0,  0],
       [ 0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [53]:
grid = move(grid)
grid

array([[0, 0, 0, 1, 0],
       [0, 0, 2, 8, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 8, 1, 0],
       [0, 0, 0, 0, 2]])

In [44]:
grid = move(grid)
grid

array([[0, 0, 2, 0, 1],
       [0, 0, 0, 0, 0],
       [4, 0, 0, 8, 0],
       [0, 0, 0, 0, 3],
       [0, 0, 8, 0, 0]])

In [45]:
grid = move(grid)
grid

array([[1, 0, 8, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 6],
       [1, 0, 0, 8, 0],
       [0, 0, 2, 0, 0]])

In [46]:
grid = move(grid)
grid

array([[0, 1, 0, 0, 0],
       [0, 0, 8, 0, 2],
       [0, 0, 0, 4, 0],
       [0, 1, 2, 0, 0],
       [0, 0, 0, 8, 0]])

In [47]:
grid = move(grid)
grid

array([[ 0,  0,  1,  8,  2],
       [ 0,  0,  0,  0,  0],
       [ 0,  0, 14,  0,  0],
       [ 0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [48]:
grid = move(grid)
grid

array([[0, 0, 0, 1, 0],
       [0, 0, 2, 8, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 8, 1, 0],
       [0, 0, 0, 0, 2]])

In [36]:
grid = move(grid)
grid

array([[ 0,  1,  1,  9,  2],
       [ 0,  0,  0,  0,  0],
       [ 0,  0, 14,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [37]:
grid = move(grid)
grid

array([[0, 0, 1, 1, 1],
       [0, 0, 2, 8, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 8, 0, 0],
       [0, 0, 0, 0, 2]])